### ISSUE TITLE
Unable to set bookkeeperJVMOptions 

### ISSUE THREAD

**Issue by dandaoatdell** [pravega/bookkeeper-operator#32]
Attached is our bookkeeper.yaml. The deployment goes fine. However, none of the parameters in the bookkeeperJVMOptions are being set. 

[bookkeeper.yaml.txt](https://github.com/pravega/bookkeeper-operator/files/4530149/bookkeeper.yaml.txt)

For example we are expecting the   "-XX:MaxDirectMemorySize=8g"]

However, it's still set at 1g:

[root@pravega-bookie-0 bookkeeper]# env | grep BOOKIE
BOOKIE_MEM_OPTS=-Xms1g -XX:MaxDirectMemorySize=1g -XX:+ExitOnOutOfMemoryError -XX:+CrashOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/dumpfile/heap -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2

**Comment by RaulGracia** [comment]
@dandaoatdell I have talked to @pbelgundi and it looks like the right field to set in the manifest is `jvmOptions`, not `bookkeeperJVMOptions`. This means that the documentation is wrong and should be fixed, but please try to modify your manifest accordingly to see if it works. @SrishT @Prabhaker24 can you please fix the documentation so `jvmOptions` is used instead of `bookkeeperJVMOptions`? Thanks!

**Comment by dandaoatdell** [comment]
We use the jvmOptions and it works. Thanks
